plot_rr_gauss <- function(results, n_dim, rho) {
  ggplot(results, aes(x = alpha, y = mean_rejection_rate, color = statistic, fill = statistic)) +
    geom_line() +
    geom_point() +
    geom_ribbon(aes(ymin = mean_rejection_rate - se_rejection_rate, ymax = mean_rejection_rate + se_rejection_rate), alpha = 0.2) +
    labs(title = paste("Rejection Rates by Alpha with SE Bands,\nData Generated by Gaussian Method, ρ = ", rho,
                       ", d = ", n_dim, sep = ""), 
         x = "Significance Level (alpha)", y = "Rejection Rate") +
    theme_minimal()
}
