# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function to compute the Gaussian kernel matrix
#' 
#' @param data A numeric matrix of data points
#' @param sigma A numeric value for the bandwidth of the kernel
#' @return A numeric matrix of the kernel matrix
cpp_gaussKern <- function(data, sigma) {
    .Call(`_mydHSIC_cpp_gaussKern`, data, sigma)
}

#' Function to compute the linear kernel matrix
#' 
#' @param data A numeric matrix of data points
#' @return A numeric matrix of the kernel matrix
cpp_linearKern <- function(data) {
    .Call(`_mydHSIC_cpp_linearKern`, data)
}

rcpp_hello_world <- function() {
    .Call(`_mydHSIC_rcpp_hello_world`)
}

