// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_gaussKern
NumericMatrix cpp_gaussKern(NumericMatrix data, double sigma);
RcppExport SEXP _mydHSIC_cpp_gaussKern(SEXP dataSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gaussKern(data, sigma));
    return rcpp_result_gen;
END_RCPP
}
// cpp_linearKern
NumericMatrix cpp_linearKern(NumericMatrix data);
RcppExport SEXP _mydHSIC_cpp_linearKern(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_linearKern(data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _mydHSIC_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mydHSIC_cpp_gaussKern", (DL_FUNC) &_mydHSIC_cpp_gaussKern, 2},
    {"_mydHSIC_cpp_linearKern", (DL_FUNC) &_mydHSIC_cpp_linearKern, 1},
    {"_mydHSIC_rcpp_hello_world", (DL_FUNC) &_mydHSIC_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_mydHSIC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
